### ISSUE TITLE
Problema con Flask en Mac

### ISSUE THREAD

**Issue by rmenor** [livrasand/Kingdom-Hall-Attendant#15]
Si usas mac y te dice:
ERROR: Could not find a version that satisfies the requirement kivy-deps.sdl2==0.7.0 (from versions: none)
ERROR: No matching distribution found for kivy-deps.sdl2==0.7.0

Prueba a crear un entorno virtual

python3 -m venv .venv
. .venv/bin/activate

Luego instala flask

pip install Flask

Vuelve a ejecutar 

python3 app.py

**Comment by livrasand** [comment]
Hola mi hermano Ramón, muchas gracias por el dato, voy a revisar...

**Comment by livrasand** [comment]
¿Cómo obtuviste el error? ¿Clonaste el repositorio? ¿En la Web o en la app para MacOS?

**Comment by rmenor** [comment]
Hola, tengo un mac mini con sonoma y me pasó después de clonar el repositorio y seguir los pasos de instalación que indicas.

**Comment by livrasand** [comment]
De acuerdo, muchas gracias @rmenor, revisaré el problema...

**Comment by livrasand** [comment]
Intente probar ahora mi hermano @rmenor, haber si le funciona por favor.
