### ISSUE TITLE
PROBLEMA

### ISSUE THREAD

**Issue by jaacyrcg** [livrasand/Kingdom-Hall-Attendant#36]
Hola,

Por alguna razón, no me es posible seleccionar un hermano cómo superintendente de grupo en la sección de Grupos para el servicio del campo aunque en su perfil lo seleccione como tal y tampoco me deja escoger al auxiliar de grupo aunque lo marque como tal en su perfil, lo extraño es que en el caso del auxiliar, aveces aparece para elegirlo y aveces no.

En la seccion de Vida y Ministerio, cómo se puede editar o eliminar un programa que se ha hecho por error?

Gracias por la ayuda y la atención prestada.
Aprecio mucho el trabajo y esfuerzo invertido en este proyecto.

Un abrazo

**Comment by livrasand** [comment]
Hola, estuve revisando el problema que me comentó, debe eliminar el grupo que hizo ya anteriormente y que no le permite añadir un nuevo superintendente auxiliar, y crear uno nuevo y antes de guardarlo seleccione a su superintendente y a su auxiliar, entonces podrá guardarlos ahora sí, voy a trabajar en esto para que, aunque esté guardado, muestre de todas maneras los superintendentes o auxiliares que ya tenga previamente registrados. Saludos! Verá una actualización pronto 😉

**Comment by livrasand** [comment]
Gracias @jaacyrcg , ahí está la actualización con la corrección de errores, y también tus créditos por la ayuda.
