### ISSUE TITLE
Error al iniciar sesion

### ISSUE THREAD

**Issue by iquirozGh** [livrasand/Kingdom-Hall-Attendant#37]
Al momento de iniciar sesion aparece el error: Ha ocurrido un error interno con la base de datos: no such column: idioma.

(me llega el correo de inició de sesión correcto)

![image](https://github.com/user-attachments/assets/08ed75f1-eb3b-4cac-b35d-eac4287351c8)

PD: Excelente programa el que están desarrollando

**Comment by livrasand** [comment]
Hola mi hermano! Podría decirme cuál es su correo electrónico por favor? Con el que se registró en KHA. Aunque actualicé todas las bases de datos (según yo 😅) por alguna razón se me pasó la suya yo creo. Y muchas por el buen comentario, es alentador y se siente bien que les guste a ustedes y sobre todo, que les sea útil.

**Comment by iquirozGh** [comment]
Hola!

Mi correo es ***@***.***

Muchas gracias por el programa. Actualmente estamos usando AQUILA para llevar los registros, pero nos complica El tema de la sincronización vía Dropbox. Así que queremos comenzar a utilizar ambos programas a la espera de que puedan habilitar el módulo de informes de servicio. Llegando a ese punto dejaríamos AQUILA y nos cambiamos a KHA contribuyendo anualmente con el modo Golden, y así colaborar con el desarrollo y mantenimiento de los servidores.


Gracias por el programa, facilita mucho las actividades.

Atte.

Iván Quiroz

**Comment by livrasand** [comment]
Muchas gracias mi hermano por sus buenas intenciones! La valoro mucho. Parece ser que GitHub bloqueó el correo electrónico, envíame un correo a livrasand@outlook.com. Muchas gracias mi hermano.

**Comment by iquirozGh** [comment]
Muchas gracias, el problema fue solucionado .
