### ISSUE TITLE
Cambio de contraseña

### ISSUE THREAD

**Issue by iquirozGh** [livrasand/Kingdom-Hall-Attendant#40]
Hola nuevamente! 

¿Cómo puedo cambiar la contraseña de acceso? Voy a compartir el acceso con otros miembros pero no quiero exponer la actual clave.

**Comment by livrasand** [comment]
Hola. Por el momento no hay una función para crear una contraseña compartida. La contraseña actual será la que todos poseerán. Sin embargo, es posible cambiar la contraseña actual. Pero, la única forma actual de cambiarla es manualmente, permítame crear la función "Cambiar la contraseña" en estos próximos días. Le haré saber por este medio cuando la función esté integrada. Y además, es una muy buena idea crear una contraseña compartida 👍🏻 veré que puedo hacer para el futuro e integrar una función para invitar a miembros y seleccionar las funciones a las que tendrá acceso.

**Comment by livrasand** [comment]
Hola @iquirozGh ! Ya es posible cambiar su contraseña, puede hacerlo desde su cuenta, en configuración, verá la opción "Cambiar contraseña".
